### PR TITLE
Add support for iMX.6

### PR DESCRIPTION
**Pull request by warped-rudi**
Finally... This patch set adds support for the iMX.6 SoC. It is based on the original code by @wolfgar from 2014. Even though it should work with his original kernel driver, it's suggested to use [this driver](https://github.com/SolidRun/linux-fslc/pull/42). So far it has only been tested with the 'official' SolidRun 3.14.xx series kernels.

### CODE REVIEW

**Comment by dougnazar** [comment]
Ironically I spend an hour today updating it too before I thought to check if there was a pull request. I only use the basics (on, off, etc) but it works fine for me on several i.MX6 devices and various TVs.

Thanks,
Doug

**Comment by opdenkamp** [comment]
I'll have to check this after doing a minor release with fixes. Thanks :)

**Comment by warped-rudi** [comment]
This stuff is compatible with SolidRun's 3.x and 4.9.x kernels for iMX.6, which in turn are derived from the chip vendor's non-mainline kernels. It appears that SolidRun is working on a unified 4.9 for all their iMX products and I guess/hope that we we can use this code for iMX.8 as well. But it could also be, that iMX.8 will be using the newer kernel CEC framework.

**Comment by opdenkamp** [comment]
@warped-rudi sorry for the delay. If this PR is still relevant with the current iMX hardware/software, could you then rebase it so I can include it in the upcoming release. Also, if you haven't signed this yet, please take a look at https://www.pulse-eight.com/contributors

If it's all using the Linux in-kernel implementation now, then this is no longer needed. Thanks

**Comment by warped-rudi** [comment]
@opdenkamp I rebased to the patch and did a quick test t verify that it works on an older iMX.6 board. I kinda lost track of the current status of the iMX.6 mainline support, but AFAIK it's still not as good as the old vendor kernels with respect to multimedia. Therefore I'd like to see it included. As for the contributors agreement: I'm pretty sure that I already signed it when I submitted the TDA995x stuff many years ago.

**Comment by opdenkamp** [comment]
Thanks for the update and for the patch. There are a couple of small cosmetic issues that I'll fix up later.

**Comment by warped-rudi** [comment]
Talking about cleanup: It appears that all of the "custom" adapters implement a member function named 'XXXCECAdapterCommunication::HandleLogicalAddressLost()'. I think this is a leftover from earlier days and is not needed anymore.

**Pull request merged**
