### PR TITLE
RFC: Linux CEC framework adapter

### PR DESCRIPTION
**Pull request by Kwiboo**
This is a request-for-comment for a linux cec framework adapter, any feedback would be grateful.

Tested on a ROCK64 device running LibreELEC+Kodi using the dw-hdmi-cec kernel device.

### CODE REVIEW

**Comment by opdenkamp** [comment]
Just letting you know that I did see this PR, but I haven't had time yet to look into it because of other priorities. I'll look into it (and other PRs) asap. Thanks

**Comment by Hedda** [comment]
@opdenkamp any update on this? ..any chance it will make the next major release of LibCEC?

https://github.com/Pulse-Eight/libcec/issues/67

**Comment by nkichukov** [comment]
Hello, 
I have successfully applied the patch from the pull request to raspberry pi 3B running the kernel HDMI CEC framework on raspberry-pi sources version 4.15.0-rc7. It is a 32bit arm Gentoo Linux installation and the remote control for my Samsung TV is now able to control kodi! Initialization works, some errors are reported, but do not prevent any signalling:
```
22:33:18.511 T:1859122160  NOTICE: Register - new cec device registered on cec->Linux: CEC Adapter (0000:0000)
22:33:18.514 T:1824650224   ERROR: CecLogMessage - CLinuxCECAdapterCommunication::Write - ioctl CEC_TRANSMIT failed - tx_status=00 errno=1
22:33:18.702 T:1945591824   ERROR: Previous line repeats 3 times.
```
I have prepared custom ebuild with the patch and two changes to configuration:
-DHAVE_LINUX_API=1 and -DHAVE_RPI_API=0.

This is based on libcec-4.0.2.
Thanks a lot for implementing this functionality! This is greatly appreciated. Hope this makes it into mainline libcec any time soon!

Cheers,
-Nik

**Comment by Kwiboo** [comment]
@nkichukov thanks, I have seen similar errors happening during first initialization, but since it works after that I have just ignored it.
Great to have confirmation that this adapter also works with other cec framework drivers beside the dw-hdmi-cec driver.

Also note that this adapter has some limitations like only supporting `/dev/cec0`, but is complete enough for use with Kodi+LibreELEC.

**Comment by Hedda** [comment]
@opdenkamp any chance that this Linux kernel CEC framework adapter is still on your roadmap for libcec?

**Comment by TheNetStriker** [comment]
I've just tested this on a Rock Pi 4 and it works. When will this be merged into the main branch?

**Comment by Hedda** [comment]
@opdenkamp any more feedback on blockers and/or showstoppers for this PR?

**Comment by opdenkamp** [comment]
I just wanted to pull this one in, but it looks like one last thing is missing before I can do this. @Kwiboo could you take a look at https://www.pulse-eight.com/contributors please. I'll merge it in once this has been signed. Sorry for the (massive) delay.

**Comment by MilhouseVH** [comment]
FYI this PR and latest libcec master results in this build failure: https://github.com/Pulse-Eight/libcec/commit/cb3cc570855ec3dd32b43a3b1405da0e550abf62

**Comment by opdenkamp** [comment]
see https://github.com/Pulse-Eight/libcec/commit/cb3cc570855ec3dd32b43a3b1405da0e550abf62#commitcomment-38206215

**Comment by Kwiboo** [comment]
@opdenkamp thanks for the tip, I will update the PR and send in a signed CLA (as soon as I have access to a printer/scanner)

**Comment by malard** [comment]
You can use your phone :)

Sent from my Huawei phone


-------- Original message --------

**Comment by Kwiboo** [comment]
@malard thanks, I used Adobe Fill & Sign to sign the CLA.

**Comment by MilhouseVH** [comment]
Confirming that this PR now builds with the `GetStats()` commit - thanks!

**Comment by Hedda** [comment]
@opdenkamp Does adding Linux CEC framework adapter warrant a major version change for libcec?

That is, will Linux CEC framework support in libcec = libCEC 5.0 (v5.0.0) version release, or?

**Comment by opdenkamp** [comment]
@Hedda not this specific PR, but another one that got merged does

@Kwiboo could you email the signed CLA directly to martin.ellis[at]pulse-eight.com please. thanks

**Comment by Kwiboo** [comment]
@opdenkamp I have now sent the signed CLA directly to @malard email, the initial email to contributor-agreement[at]pulse-eight.com bounced.

**Comment by malard** [comment]
Not sure why, but thanks, all received

**Comment by tomillr** [comment]
Could someone clarify what the benefit of the Linux CEC framework is compared to the old way of doing things?

Does it mean, that any Linux system running a later kernel version automatically supports the Pulse-Eight CEC devices without the need to manually install drivers or libCEC packages?

I'm curious because I'm to get some of the linux-based Retro-Gaming distros like Lakka, Recalbox or Batocera to work with my Pulse Eight CEC adapter on a x64 system. Is there an easy way to implement basic CEC features like turning on a tv and switching the HDMI input?

**Comment by mlindner** [comment]
> Could someone clarify what the benefit of the Linux CEC framework is compared to the old way of doing things?
> 
> Does it mean, that any Linux system running a later kernel version automatically supports the Pulse-Eight CEC devices without the need to manually install drivers or libCEC packages?
> 
> I'm curious because I'm to get some of the linux-based Retro-Gaming distros like Lakka, Recalbox or Batocera to work with my Pulse Eight CEC adapter on a x64 system. Is there an easy way to implement basic CEC features like turning on a tv and switching the HDMI input?

My rough understanding is that this is a completely separate CEC effort as part of the Linux kernel. There's numerous CEC devices in various hardware that are supported now by recent Linux kernels. This adds support to libcec to control these linux kernel CEC devices. For example I believe you can even turn GPIO pins directly into CEC output and input pins with the kernel driver, if your computer/device has such pins.

**Pull request merged**
