### PR TITLE
use system audio mode request instead of power on to start AVR reliable

### PR DESCRIPTION
**Pull request by gdachs**
It seems to be the right thing, the old code is not reliable.

### CODE REVIEW

**Comment by popcornmix** [comment]
We've added this to Milhouse nightly builds on Pi.
Prior to this, powering on Panasonic TV resulted in Onkyo receiver powering on, then off then on again. While that is tolerable, it is pretty slow.
With the PR in place the Onkyo just powers on one as desired.

**Comment by Theetjuh** [comment]
Thanks for the notification!
Lets hope Sam takes this along with OSMC aswell :)

**Comment by dsebastien** [comment]
Great! Where can I download the nightly build for Rpi?

**Comment by popcornmix** [comment]
Milhouse nightly builds are here: http://forum.kodi.tv/showthread.php?tid=250817

**Comment by dsebastien** [comment]
Heh, I just noticed the link in the last post, thanks!
I'll try this out right away and report back. This has been driving my wife crazy(ier) :)

**Comment by dsebastien** [comment]
Mh, are there specific install guidelines?
I've tried three times without success:
- copied the tar file two times to the update folder
- uncompressed and copied KERNEL & SYSTEM files to the update folder

The checks of those files seem ok but then I get: "checking size: failed". Any idea?

I've used that file on a RPi 1: http://milhouse.openelec.tv/builds/master/RPi/OpenELEC-RPi.arm-8.0-Milhouse-20160319230441-%230319-g0026734.tar

**Comment by popcornmix** [comment]
Ask in the thread. This isn't the right place to troubleshoot installation issues.

**Comment by samnazarko** [comment]
I put this patch in over the weekend and didn't have any negative reports, except one: https://discourse.osmc.tv/t/2016-02-4-cec-partial-fail-on-input-change-to-osmc/15031 which I already emailed @gdachs about today and he says that it is somewhat expected behaviour. 

The user has posted Debug logs

**Comment by Theetjuh** [comment]
I haven't had any issues any more, will let it know here when I know more.

**Comment by gdachs** [comment]
@samnazarko: No, I didn't say that it is expected behavior. I just can't see what is wrong with my change, it corresponds to the hdmi cec specification. I have tested with my Samsung TV, Denon AVR, Wetek Core and Play with OpenELEC and a Nvidia Shield TV. I can't see this problem.

**Comment by opdenkamp** [comment]
this one will be merged in but a little different as how it's done here so it uses the internal apis

**Pull request closed without merging**
