### PR TITLE
Fix LG TV always changing input when turned on #307

### PR DESCRIPTION
**Pull request by maart84**
Same as pull request #372 but cleaned it up. This fixes issue #307 & issue 1 from #344.

### CODE REVIEW

**Comment by meetpraveen** [comment]
OK repeating the question here, is there any plan to get this merged? If not, how can I patch my liberelec with this fix? I can help in testing if you can provide the patching details.

**Comment by maart84** [comment]
As far as I know, you have to build it from source. You can use mine if you want. It's based on LibreElec sources from a few days ago, but I'm not having any issues. 

https://maart84.stackstorage.com/s/5g6Am7wbiSqtnD1

**Comment by meetpraveen** [comment]
Sorry for the noobs question, but how do I lay it over to my existing liberelec? I see a .kernel, .system and a .tar file in the location you have shared. Do I have to flash my pi with those, or I can just extract it over the existing installation? If there is any existing doc, it would be great.

**Comment by maart84** [comment]
Just put all files in the /storage/.update folder of your RPI. Or use the network share of your RPI: \\yourRPI\Update. Reboot and it will update.

**Comment by meetpraveen** [comment]
Thanks @maart84 for the steps. I tried it, but the patch disabled CEC totally. There were a lot of other issues like vnc and smb stopped working. A lot of my plugins got disabled. I was on 8.0.2. I was trying to create a custom build myself. How do I build it from source?

**Comment by maart84** [comment]
This is a good place to start: https://wiki.libreelec.tv/compile. I've added a 8.0.2 build as well to that folder, but haven't tested it myself. Feel free to give it a try

**Comment by stedaniels** [comment]
This PR fixes the problem of all LG 2012 TV's having their input stolen by the Pi every time they're turned on.  (The problem was created by a fix for one guys problem.)  Any news on when it'll be merged?

**Comment by WilcoVertegaal** [comment]
Yes please, merge this so we can test it with the Kodi 18 test builds.

**Comment by Raybuntu** [comment]
I will test this with my LibreELEC builds. It might be worth including the PR as a patch in LibreELEC as long it's not fixed upstream a.k.a here.

**Comment by maart84** [comment]
If someone needed help with building this in Libreelec: I've written a patch as well: https://pastebin.com/raw/9ZC0syiV
download this patch in the LibreELEC.tv and run it as 'patch -p1 < downloadedfile'
it patches 3 files:
- change libcec package version to 8adc786 (latest)
- create a patchfile which includes this fix
- create a patchfile with some build error I got about ltinfo in the latest libcec package

after that you can build Libreelec.

**Comment by Raybuntu** [comment]
@maart84 Is it really required to bump libcec to latest?

**Comment by maart84** [comment]
No probably not, but there was also some other fix for my LG tv when paused videos resumed automatically (issue:[344](https://github.com/Pulse-Eight/libcec/issues/344) nr 2) which was fixed somewhere along the way.

**Comment by Raybuntu** [comment]
I don't have the other issue. I've been testing the PR without the libcec bump and it's working very good.
@maart84: Considering this PR is rotting for 2 months now would you be willing to PR your PR as a Patch to LibreELEC master? We can easily drop it when this gets merged and we bump libcec.

**Comment by maart84** [comment]
@Raybuntu Sure! if you tell me how I do that.

**Comment by Raybuntu** [comment]
@maart84: I've done it like this in my personal tree:
https://github.com/Raybuntu/LibreELEC.tv/commit/0a14e95d09cd459afdd9bb00c4859361c4a7190e

However this was just quick and dirty. Normally I would do it like that:
In libcec git directory checkout the sha that's used in LE. Make your changes and commit those. Then use git format-patch to get a proper formated patch with author attribution.
Then fork and clone the LE git. Add your patch to the location like in my example commit. Create a PR through Github.

But if you want I can PR it to LibreELEC too if it's too much work for you?

**Comment by anomaly256** [comment]
@malard @popcornmix why isn't this merged yet?  What's happening?

**Comment by opdenkamp** [comment]
this breaks input switching on older LG TVs. I'm looking into it

**Comment by anomaly256** [comment]
How old?  I’ve tested this on a pre webos 60lm6450

**Comment by meijjaa** [comment]
Thanks Maart, this fixes the problem for me as well (AML S905X box, LG 55C6 TV, Denon AVR-X3300). The box keeps on stealing input when I try to switch to my Chromecast though :( .

**Comment by cdwertmann** [comment]
I can confirm that the patch that was merged into LibreELEC master branch above fixed the issue on my 2017 LG OLED TV when using the latest LibreELEC alpha release (8.90.005). It is not included in the stable 8.2.5 release.

**Comment by opdenkamp** [comment]
Sorry for the long delay. Since I can only reproduce this on a pretty old (2007) TV and I haven't heard any complaints from *Elec users, I'm merging this in. Thanks

**Comment by stephenwade** [comment]
@opdenkamp Does the latest version available at [the download page](http://libcec.pulse-eight.com/Downloads) include this fix?

**Comment by opdenkamp** [comment]
@stephenwade ah no, thanks for letting me know, we'll update it. you can find the files here: https://github.com/Pulse-Eight/libcec/releases/tag/libcec-4.0.3

**Comment by anomaly256** [comment]
Thank you @opdenkamp

**Pull request merged**
