### PR TITLE
Add support for NetBSD.

### PR DESCRIPTION
**Pull request by jaredmcneill**

### CODE REVIEW

**Comment by opdenkamp** [comment]
looking good, thanks!
but before we can accept this code, we have to ask you to read and sign http://www.pulse-eight.net/contributors

**Comment by opdenkamp** [comment]
Hi @jaredmcneill I couldn't find the contributor agreement. Did you accept it and send it to contributor-agreement@pulse-eight.net?

**Comment by opdenkamp** [comment]
Hi @jaredmcneill I'd like to include your patch, but I didn't get any response to the question about the contributor agreement (http://www.pulse-eight.net/contributors).

**Comment by Hedda** [comment]
@jaredmcneill any chance you could respond to the linked contributor agreement?

**Comment by Hedda** [comment]
@jaredmcneill any chance you could update this and sign out the linked contributor agreement?

https://www.pulse-eight.com/contributors

I read now that best if you could email the signed CLA directly to martin.ellis[at]pulse-eight.com

Alternatively, should also be able to on your smartphone use Adobe Fill & Sign to sign the CLA.

**Comment by Hedda** [comment]
@jaredmcneill any chance you could update this and sign out the linked contributor agreement? Required for https://github.com/Pulse-Eight/libcec/pull/120

https://www.pulse-eight.com/contributors

**Pull request closed without merging**
