### PR TITLE
Added LG-Reconnect-Request

### PR DESCRIPTION
**Pull request by Vollstrecker**
Just ignoring the command, doesn't work. My Pc even doesn't notice that it is the active source, and without reconnecting it never gets any input.

Here is my solution, which is working for quite some time now.

### CODE REVIEW

**Comment by opdenkamp** [comment]
Ok thanks, I'll give this a go with the LGs that I have here.

Could you clean up the patch a bit to get rid of the reordered code. This changes 10 lines, while the actual fix for you is just the added `HandleVendorCommandPowerOn()` call + the cosmetic name change of the #define. Thanks

**Comment by Vollstrecker** [comment]
If you like an easier to read patch more, for sure I can, but to be honest: I like to have 0x0b before 0xa0.

**Comment by opdenkamp** [comment]
You're right, been looking at this code for too long and didn't spot that. nvm the cosmetics.
I've tested it on one of the LGs that I have here, and it doesn't break things on that one, but I didn't see 0x0b anywhere in the log, so it looks like this one isn't sending it. I'll try a more recent one in a bit, thanks.

**Comment by Vollstrecker** [comment]
It's an 55LF6309 with current WebOS Version. From the energylabel it was introduced in late 2014. Unfortunatele I can't tell if the command was sent before the webOS update.

**Comment by opdenkamp** [comment]
The webos version can be found in the TV's menu, if you go to "about this TV". My most recent one is 2.0

**Comment by Vollstrecker** [comment]
On TV-menu I get 04.05.1, but maybe it's a "feature" of LF-Series or something else. I don't think someone can tell us.

**Comment by opdenkamp** [comment]
That's the same version as mine is running, so I should be able to reproduce this, thanks

**Comment by jfjm** [comment]
With this change, it is causing the issue of TV switching source to the device using libece when TV turns on (regardless what the previous source was on).

**Comment by Vollstrecker** [comment]
I'm sure it's no general side-effect, as my  device does't show that problem. 

I think the reconnect  is working as expected  and maybe  some  new vendorspecific thing appeared.

**Comment by anomaly256** [comment]
My tv is an 60LM6450, quite old now and predates WebOS.  It was working fine previously but now switches to the source Kodi is on every time the TV powers on.  Judging by the responses in #307 this is causing more problems than it fixes, if it is indeed the change that caused it

**Comment by anomaly256** [comment]
Is the addition of HandleVendorCommandPowerOn() intended here?  This calls device->MarkAsActiveSource() in SLCommandHandler.cpp

**Comment by jfjm** [comment]
There are few threads with many people at the OSMC forum reporting the LG TV automatically switching source after updated to the new Kodi version. Initial effort was focused on if changes in OSMC or Kodi caused the behavior change, but it was narrowed down to the change in libcec. Based on the the logs provided in [#307,](https://github.com/Pulse-Eight/libcec/issues/307) the  symptoms, and the changes, they match perfectly.

Note, my LG model is 55LS5700, a 5 years old TV. It was also working fine with 3.x version, and now switch source every time TV turns on.

**Comment by mfarrell34** [comment]
I've done some testing on my LG 65UF6450 with and without the SL_COMMAND_REQUEST_RECONNECT being handled and confirmed that removing this change and ignoring the 0b vendor command stops the input switching issue from occurring. When testing with lib-cec on a raspberry pi, I found:

-Regardless of whether the 0b command is handled or not, if SIMPLINK auto power sync was not enabled on my TV when turning on my TV by sending 'on 0' it would hang on the power status 'in transition from standby to on' and repeatedly broadcast device vendor id requests. Therefore I have to enable auto power sync mode on my TV in order to turn it on via a cec command.

-With auto power sync on my TV would request the cec adapter's physical address and vendor id. After receiving a response from the adapter my TV sent several 0b vendor commands followed by a 01 INIT vendor command, and then request the adapter device's power status. The adapter device's power status had been changed to standby during the INIT command handling, and then the power status was updated to 'on' during the REQUEST_POWER_STATUS command handling. This seems to indicate the adapter hadn't been the active source prior to this point (unless I'm reading it wrong and my raspberry pi wasn't the destination of the command). With the 0b command being ignored the active source was never set by the adapter, so the TV turned on and remained on the same input it had been on prior to being turned off.

What information indicated the 0b command was a reconnect request? I saw two 0b vendor commands followed by a 01 vendor command after the TV had already requested and received the adapter's physical address and vendor id. 

I think the key difference in whether the input of the TV changes after it's powered on is whether the device had been marked as the active source prior to this. When HandleVendorCommandPowerOn is called to handle the 0b commands being received, this is marking the device as the active source which is then passed to the TV after it turns on and requests the active source. Also I never saw the 03 POWER_ON command from my TV when testing, it could vary from TV to TV but it doesn't seem correct that the power on command handler would be getting called before the init command handler, unless I'm misunderstanding.

**Comment by Vollstrecker** [comment]
The reason for just ding the reconnect was, that after turning the TV off, Everest time I  got 0b, Ich had to reconnect. Otherwise the TV didn't communicate with the adapter at all.

The cause for using The PowerON method was just, that I didn't find any other way to get that done. 

I can't search the part would have preffered atm, as I'm away from home since 2 weeks now, and doing this search on my mobile isn't any sort of fun. 

Btw: my TV doesn't change the source in the described situation.

**Pull request merged**
