### PR TITLE
Update pyCecClient.py

### PR DESCRIPTION
**Pull request by nlrb**
Fix unknown variable CECDEVICE_BROADCAST

### CODE REVIEW

**Comment by opdenkamp** [comment]
Thanks! Before we can accept any code, could you read and sign http://www.pulse-eight.net/contributors please.

**Comment by nlrb** [comment]
Hi Lars,

Ik zal het morgen eens lezen. Maar deze fix is zo simpel, die kan je zelf ook verzinnen ;-).

Grtz,
-Ramón

Verstuurd vanaf mijn iPad

**Comment by nlrb** [comment]
I've read the Pulse-Eight Contributor License Agreement, but unfortunately cannot sign it. It would conflict with my employers contract. A shame really.

**Comment by malard** [comment]
It's a clone of the ubuntu agreement, it really just assigns you the right to the code, but us a license to use it and distribute it as we see fit, sorry to hear you have a restrictive employer contract!

**Pull request closed without merging**
