### PR TITLE
Modifies NSIS script to call EventGhost to install the plugin

### PR DESCRIPTION
**Pull request by kdschlosser**
This is a test run of having NSIS call EventGhost to install the plugin using the new .egplugin format. There is a bug which I have just discovered in EventGhost, I will fix in the next release but it causes EventGhost to hang if EventGhost is not already running when the installer gets launched. A simple kill of the EventGhost.exe process after the completion of the plugin installation allows the installer to continue.

Please inform me of any changes you would like to see made with this. I have released the plugin to the EG users via the forums to be able to get the kinks ironed out of it. Once I know it is good to go I will do another commit to this with the newer version of the plugin.

The .egplugin file is a zip file so you can open it up using your favorite compression utility to be able to check out the plugin code.

### CODE REVIEW

**Comment by opdenkamp** [comment]
Thanks for this, obviously a better method than blindly copying the files into the installation directory :)

One request: no binaries, but source files only. If the egplugin file is just a zip, could you then add a batch file that generates it from source. Thanks

**Comment by kdschlosser** [comment]
ok that shouldn't be an issue either. let me do some research into NSIS and seer if it has the abilities to create a zipfile.

**Comment by kdschlosser** [comment]
OK so this is the skinny. NSIS does not handle making zips at all. But this can be achieved using a VB script. and it so happens that i know not a thing about VB and the code snippets I have come across for doing this task are non functional. I managed to alter one of them and it makes the zip file but it does not move anything into it. I am not sure if this is something you could whip up or not. but a simple script that could be passed the folder to add and the output file name would be perfect. it would have to be able to add recursively. the reason why this has to be done using a VB script is because access to that part of windows can only be done through a COM object.

**Comment by opdenkamp** [comment]
You could just write a batch file that does this as part of https://github.com/Pulse-Eight/libcec/blob/master/windows/create-installer.cmd no?

**Comment by kdschlosser** [comment]
from the information I have found is that you cannot invoke the zip compression part of windows from command line. it has to be done either from PowerShell or VB script. I do not know a whole lot about the build process for libCEC. I am not sure if the build process that is set up is an "all in one" kind of a thing. where you can run a single script and when it is done you have an installer. it will co through and compile all the bits and pieces and then build the installer. of ir you have to manually build each component and then run the script to build the installer. so I do not know at what point to inject the creation of the egplugin file. if the egplugin file needs to be created before the installer gets made using create-installer.cmd the use of a PS or VB script would still be required because it is a bat file. I do want to test something because I did manage to get the zip file made i wonder if i can simply copy files into it once it is made.

**Comment by kdschlosser** [comment]
Give this last commit a shot and see if you like it. I removed the binary file, I leveraged PowerShell from a command line to create the zip file, I also added some error checking as well as file cleanup. All without the need of any additional scripts. I used the files that were already in place.

**Comment by kdschlosser** [comment]
NOTE: 
If this is acceptable please do not merge it. as the actual plugin is not fully tested as of yet. It is going to have problems I am sure. And I also wanted to add more functionality to it.

**Comment by kdschlosser** [comment]
@opdenkamp 

Is this acceptable to you for installing the egplugin?. I would like to know if i should continue my search on a way to make the zip file.

**Comment by opdenkamp** [comment]
Just took a quick look, looking good, thanks.
Wonder why MS didn't hook up something to zip from the command line without needing a crazy powershell hack though :)

**Comment by kdschlosser** [comment]
wish I knew. that is one of those questions that is right up there with why hasn't Microsoft fixed the windows message for turning the power back on to your monitors. the one they broke somewhere between windows 7 and 8. Or the why haven't they fixed the USB redirection in for RDP. the one that worked in the release candidates for windows 10 but is broken in the full release. here is another good one. how about the why does it remove all of the groups associated to all user accounts except for the one that you used to upgrade to windows 10 with? and why does it give you an error of bad password when you go to login with one of those now broken accounts when there is nothing wrong with the password at all.. 

Or the build 1607 will not disable driver signing unless it is a brand new install of windows 10 not an upgrade or an update... (achew bull^%#@)

For some reason I am thinking we will never have the answers to those questions.

but what I have done works. it is quite the hack to get it to.. but it is the only solution i could find.

**Comment by kdschlosser** [comment]
I wanted to make note. I have a more updated version of the plugin. I will submit a PR for it.
When do you think you are going to be doing a release?? I should be able to get it out to ya in the next day or to.

**Comment by opdenkamp** [comment]
I'm working on a release right now, that just includes some fixes, version 4.0.3. Your new changes can be merged in right after that release has been tagged. Same goes for some other open pull requests.

**Comment by kdschlosser** [comment]
I wanted to ask you a question in regards to swig... is there a reason as to why it is used instead of porting python.h and making wrappers. I think it would be far easier to follow. leave the core of libcec the way it is add a file that contains any python wrappers and that file can get added to the source list if it's being built for python. it would end up with a .pyd extension. but any calls can be made directly to the dll without the need of a go between. I am not sure if this is possible with libcec or not. The reason for asking this is because it seems that the majority of the data being passed between the 2 are either ints, strings or functions, nothing overly complex to be able to make wrappers for.

**Comment by opdenkamp** [comment]
it's not about complexity, but reduced amount of work to get the same api in python, less prone to things like conversion bugs, differences between the 2 apis if one gets changed without changing the other, etc.  
it also makes it possible to support wrappers for other languages like golang

**Comment by kdschlosser** [comment]
fair enough.

**Pull request merged**
