### PR TITLE
Fix LG TV always changing input when turned on #307

### PR DESCRIPTION
**Pull request by maart84**
Basically I reverted #256 and put the 0x0b after the 0xa0 command. This fixes issue #307 & issue 1 from #344. But since I did not have reconnect issues of #256,  I can't check if that returned. Maybe @Vollstrecker  can check it?

### CODE REVIEW

**Comment by Vollstrecker** [comment]
I've never had the problem that TV changed input when it is turned on, so I can't say anything on this. But from a short test I have no change so far. So in summary:

- When turning on mythtv, TV changes to that input
- When turning on the TV, it switches to the channel, where it was when turning off
- - If last chan was TV-channel, everything works
- - If last chan was HDMI, I have to change to TV and back to HDMI to get cec working (no change)

So overall summary: For me it works like it did with my change, and for me it works  like after 1a8dc6c96a1c74d2820fea1a39f4dc8057905102

If the change from HandleVendorCommandPowerOn to HandleVendorCommandPowerOnStatus helps you, I'm fine with that, because it doesn't change anything (at least for me), and I used in my patch just the first function that did what I wanted.

About the renaming: As from my tests it looked like the only possible action is to reconnect, if you get that from the TV, I would prefer to keep that name, as long as it's not clear what better name could be used, as it describes the action to take much better than a simple unkown, and if another unknown command appears, which just is there but has no effect on the normal operation, we still have unknown free for that one.

About: the reordering: It's a simple if, it doesn't has any meaning when it is handled, but as the defines are ordered by the hex-code of the commands, so I think the reorder is just wrong, and handling the commands in the order in which they are defined, give imo a much better orientation, when searching for that parts of code.

**Comment by maart84** [comment]
Thanks for the input. I'm no programmer so I basically just reverted to how it was and completely overlooked what I actually changed.. I cleaned up my mess and now I adjusted only the HandleVendorCommandPowerOn to HandleVendorCommandPowerOnStatus on the 0x0b part. I am testing if I did not bread the pause fix ( #307 issue 2) right now but so far it's working fine for me.

**Comment by meetpraveen** [comment]
Is this getting into the official build anytime soon. Or else, is there a way to patch this on my libreelec to get out of this issue?

**Comment by dbrosy** [comment]
What is happening with this fix?? is it in the official build yet? It is suck an annoying bug

**Comment by maart84** [comment]
Sorry I made a mess of this eventually (new to github...). I'll make a new request with just the right change.

**Pull request closed without merging**
