### PR TITLE
Support for ncurses. Giving the opportunity for shortcuts.

### PR DESCRIPTION
**Pull request by joao29a**
What do you guys think? If you guys like it, I'll fix the messages been printed on the console, add the parameter on help. I think this will be useful to control the TV a lot faster and easier.

### CODE REVIEW

**Comment by Hedda** [comment]
What is the status of this patch? Will it be merged into master?

**Comment by opdenkamp** [comment]
yes, we'll be updating libCEC and including patches like this soon.

**Comment by opdenkamp** [comment]
I've cleaned up and included your patch in https://github.com/Pulse-Eight/libcec/pull/65. See https://github.com/Pulse-Eight/libcec/commit/5a19cd8ccd12810fcc9cd5dbf96aa57afe8c3e41

**Comment by joao29a** [comment]
Cool! Thanks!

**Pull request closed without merging**
